#!/usr/bin/env bash
# setup-host.sh — Avalanche NixOS flake host setup
# Usage: sudo ./setup-host.sh
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
BOLD=$'\033[1m'; RED=$'\033[0;31m'; GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'; RESET=$'\033[0m'
info() { echo -e "  ${BLUE}→${RESET} $*"; }
ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
warn() { echo -e "  ${YELLOW}!${RESET} $*"; }
die()  { echo -e "\n  ${RED}✗${RESET} $*\n" >&2; exit 1; }
ask()  { read -rp "  ${BOLD}${1}${RESET} " "${2}"; }

# ── Sanity checks ─────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]]                    && die "Must run as root: sudo ./setup-host.sh"
command -v git     >/dev/null 2>&1   || die "git not found — run: nix-shell -p git"
command -v python3 >/dev/null 2>&1   || die "python3 not found"

FLAKE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$FLAKE_DIR/flake.nix" ]]      || die "flake.nix not found in $FLAKE_DIR"
[[ -d "$FLAKE_DIR/.git" ]]           || die "Not inside a git repo — git add will not work"

HOSTS_DIR="$FLAKE_DIR/hosts"
HM_DIR="$FLAKE_DIR/home/hosts"
cd "$FLAKE_DIR"

# ── Parse hosts already declared in flake.nix ────────────────────────────────
mapfile -t FLAKE_HOSTS < <(
  grep -E '^\s+[a-z][a-z0-9-]* = mkHost' flake.nix \
  | sed -E 's/\s+([a-z][a-z0-9-]*) = mkHost.*/\1/'
)
[[ ${#FLAKE_HOSTS[@]} -eq 0 ]] && die "Could not parse any mkHost entries from flake.nix"

# ── Template: hosts/<hostname>/default.nix ───────────────────────────────────
write_host_nix() {
  local hostname="$1" is_t480="$2"
  # Conditional T480 import line — trailing newline keeps nix formatting clean
  local t480_line=""
  [[ "$is_t480" == "yes" ]] && t480_line="    ../../modules/T480"$'\n'

  cat > "$HOSTS_DIR/$hostname/default.nix" << NIXEOF
# hosts/$hostname/default.nix — generated by setup-host.sh
{ config, pkgs, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/common
${t480_line}    inputs.noctalia.nixosModules.default
  ];

  networking.hostName = "$hostname";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enable = false;
  services.printing.enable = true;

  # ── SOPS ──────────────────────────────────────────────────────────────────
  # Uncomment after adding this host's age public key to secrets.yaml and
  # re-encrypting: sops updatekeys secrets/secrets.yaml
  #
  # sops = {
  #   defaultSopsFile  = ../../secrets/secrets.yaml;
  #   defaultSopsFormat = "yaml";
  #   age.keyFile      = "/home/mntn/.config/sops/age/keys.txt";
  #   secrets = {
  #     "github_email"          = { };
  #     "wifi/eduroam/email"    = { };
  #     "wifi/eduroam/password" = { };
  #   };
  # };

  system.stateVersion = "25.11";
}
NIXEOF
  ok "hosts/$hostname/default.nix written."
}

# ── Template: home/hosts/<hostname>.nix ──────────────────────────────────────
write_home_nix() {
  local hostname="$1"
  cat > "$HM_DIR/$hostname.nix" << NIXEOF
# home/hosts/$hostname.nix — generated by setup-host.sh
{ config, pkgs, ... }: {
  imports = [ ../common/core.nix ];

  # $hostname-specific packages
  home.packages = with pkgs; [

  ];

  home.file.".config/niri/config.kdl".source = ./niri.kdl;
}
NIXEOF
  ok "home/hosts/$hostname.nix written."
}

# ── Patch flake.nix: insert new mkHost entry ──────────────────────────────────
# Inserts immediately after the last existing mkHost line, matching
# the 8-space indent used in the nixosConfigurations block.
add_to_flake() {
  local hostname="$1"
  python3 - "$hostname" << 'PYEOF'
import sys

hostname = sys.argv[1]
with open("flake.nix") as f:
    lines = f.readlines()

# Guard: already present
if any("= mkHost" in l and hostname in l for l in lines):
    print(f"  ! {hostname} already in flake.nix — skipping")
    sys.exit(0)

# Find last line that contains '= mkHost' and insert after it
indices = [i for i, l in enumerate(lines) if "= mkHost" in l]
if not indices:
    print("  ✗ Could not locate any mkHost entries in flake.nix", file=sys.stderr)
    sys.exit(1)

new_line = f'        {hostname} = mkHost {{ hostname = "{hostname}"; }};\n'
lines.insert(max(indices) + 1, new_line)

with open("flake.nix", "w") as f:
    f.writelines(lines)
print(f"  ✓ {hostname} added to flake.nix")
PYEOF
}

# ═════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}❄  Avalanche — Host Setup${RESET}"
echo "────────────────────────────────────────────"
echo "  1) Assign this machine to an existing flake host"
echo "  2) Register this machine as a brand-new host"
echo "────────────────────────────────────────────"
ask "Option [1/2]:" OPTION

# ── Option 1 — existing flake host ───────────────────────────────────────────
if [[ "$OPTION" == "1" ]]; then
  echo ""
  info "Hosts declared in flake.nix:"
  PS3="  Select host: "
  select HOSTNAME in "${FLAKE_HOSTS[@]}"; do
    [[ -n "$HOSTNAME" ]] && break
    warn "Invalid selection — try again."
  done

  HOST_DIR="$HOSTS_DIR/$HOSTNAME"
  HM_FILE="$HM_DIR/$HOSTNAME.nix"

  if [[ ! -d "$HOST_DIR" ]]; then
    # Host is in flake.nix but was never scaffolded on disk (e.g. pheobe, aether)
    warn "'$HOSTNAME' has no host directory yet — scaffolding now..."
    ask "Is this a ThinkPad T480? [y/N]:" T480_RAW
    IS_T480="no"; [[ "$T480_RAW" =~ ^[Yy]$ ]] && IS_T480="yes"
    mkdir -p "$HOST_DIR"
    info "Generating hardware-configuration.nix..."
    nixos-generate-config --show-hardware-config > "$HOST_DIR/hardware-configuration.nix"
    ok "hardware-configuration.nix generated."
    write_host_nix "$HOSTNAME" "$IS_T480"
  else
    # Directory exists — optionally refresh hardware config for this machine
    ask "Regenerate hardware-configuration.nix for this hardware? [y/N]:" REGEN
    if [[ "$REGEN" =~ ^[Yy]$ ]]; then
      info "Regenerating hardware-configuration.nix..."
      nixos-generate-config --show-hardware-config > "$HOST_DIR/hardware-configuration.nix"
      ok "hardware-configuration.nix updated."
    fi
  fi

  # Scaffold home config if missing (e.g. host dir existed but hm file did not)
  if [[ ! -f "$HM_FILE" ]]; then
    warn "home/hosts/$HOSTNAME.nix not found — creating stub..."
    write_home_nix "$HOSTNAME"
  fi

# ── Option 2 — brand-new host ─────────────────────────────────────────────────
elif [[ "$OPTION" == "2" ]]; then
  ask "Hostname (lowercase, hyphens allowed):" HOSTNAME
  [[ -z "$HOSTNAME" ]]             && die "Hostname cannot be empty."
  [[ "$HOSTNAME" =~ [^a-z0-9-] ]] && die "Hostname must be lowercase alphanumeric + hyphens only."

  for h in "${FLAKE_HOSTS[@]}"; do
    [[ "$h" == "$HOSTNAME" ]] && die "'$HOSTNAME' is already declared in flake.nix — use option 1."
  done
  [[ -d "$HOSTS_DIR/$HOSTNAME" ]] && die "Directory hosts/$HOSTNAME already exists."

  ask "Is this a ThinkPad T480? [y/N]:" T480_RAW
  IS_T480="no"; [[ "$T480_RAW" =~ ^[Yy]$ ]] && IS_T480="yes"

  mkdir -p "$HOSTS_DIR/$HOSTNAME"
  info "Generating hardware-configuration.nix..."
  nixos-generate-config --show-hardware-config > "$HOSTS_DIR/$HOSTNAME/hardware-configuration.nix"
  ok "hardware-configuration.nix generated."
  write_host_nix  "$HOSTNAME" "$IS_T480"
  write_home_nix  "$HOSTNAME"
  add_to_flake    "$HOSTNAME"

else
  die "Invalid option — expected 1 or 2."
fi

# ── Stage all new/modified files ─────────────────────────────────────────────
# Flakes ignore untracked files; git add is required before nixos-rebuild/install.
info "Staging files..."
git add \
  "$HOSTS_DIR/$HOSTNAME/" \
  "$HM_DIR/$HOSTNAME.nix" \
  "$FLAKE_DIR/flake.nix" 2>/dev/null || true
ok "Files staged."

# ── SOPS reminder ─────────────────────────────────────────────────────────────
echo ""
warn "SOPS: your age key must be present at /home/mntn/.config/sops/age/keys.txt"
warn "      before deploying, or secret decryption will fail at activation."
warn "      To derive the key from an existing age identity:"
warn "      age-keygen -o /home/mntn/.config/sops/age/keys.txt"

# ── Deploy ────────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────────"
echo "  1) nixos-install  — fresh disk mounted at /mnt"
echo "  2) nixos-rebuild  — update a running system"
echo "  3) Exit           — deploy manually later"
echo "────────────────────────────────────────────"
ask "Deploy [1/2/3]:" DEPLOY

case "$DEPLOY" in
  1)
    echo ""
    warn "The disk must be partitioned and mounted at /mnt before proceeding."
    warn "Docs: https://nixos.org/manual/nixos/stable/#sec-installation-manual-partitioning"
    ask "Proceed with nixos-install? [y/N]:" CONFIRM
    [[ "$CONFIRM" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
    info "Running nixos-install --flake .#$HOSTNAME ..."
    # --no-root-passwd: root password is managed declaratively via users.nix
    nixos-install --flake "$FLAKE_DIR#$HOSTNAME" --no-root-passwd
    ;;
  2)
    info "Running nixos-rebuild switch --flake .#$HOSTNAME ..."
    nixos-rebuild switch --flake "$FLAKE_DIR#$HOSTNAME"
    ;;
  *)
    echo ""
    ok "All files are staged. Deploy when ready:"
    echo ""
    echo -e "    ${BOLD}# Fresh install:${RESET}"
    echo -e "    nixos-install --flake $FLAKE_DIR#$HOSTNAME --no-root-passwd"
    echo ""
    echo -e "    ${BOLD}# Running system:${RESET}"
    echo -e "    nixos-rebuild switch --flake $FLAKE_DIR#$HOSTNAME"
    echo ""
    ;;
esac
