# home/hosts/haephestus.nix — generated by setup-host.sh
{ config, pkgs, ... }: {
  imports = [ ../common/core.nix ];

  # haephestus-specific packages
  home.packages = with pkgs; [

  ];

  home.file.".config/niri/config.kdl".source = ./niri.kdl;
}
