# hosts/haephestus/default.nix — generated by setup-host.sh
{ config, pkgs, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/common
    inputs.noctalia.nixosModules.default
  ];

  networking.hostName = "haephestus";

  boot.loader.grub.enable = false;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  services.printing.enable = true;

  system.stateVersion = "25.11";
}
