# hosts/haephestus/default.nix — generated by setup-host.sh
{ config, pkgs, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/common
    ../../modules/audio
    ../../modules/gaming
    inputs.noctalia.nixosModules.default
  ];

  networking.hostName = "haephestus";

  boot.loader.grub.enable = false;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  services.printing.enable = true;

  # mouse options
  services.xserver.dpi = 180;
  services.xserver.upscaleDefaultCursor = true;

  # disable fprintd
  security.pam.services.greetd.fprintAuth = false;

  # nvidia drivers
  services.xserver.videoDrivers = [ "nvidia" ];
  boot.extraModprobeConfig = "options nvidia-drm modeset=1";

  hardware = {
    graphics.enable = true;
    nvidia = {
      open = true;
      nvidiaSettings = true;
      modesetting.enable = true;
      powerManagement.enable = false;
      powerManagement.finegrained = false;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };
  };

  # custom options
  avalanche.bluetooth = {
    enable = true;
    intelCoexFix = false; # uses Realtek adapter
  };

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  hardware.firmware = [ pkgs.linux-firmware ];

  system.stateVersion = "25.11";

  # Windows drives
  environment.systemPackages = [ pkgs.ntfs3g ];
  
  fileSystems."/mnt/HDD-Bulk" = {
    device = "/dev/disk/by-uuid/3454A76254A72618";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "nofail"
      "x-systemd.automount"
      "x-systemd.idle-timeout=60"
    ];
  };
  
  fileSystems."/mnt/SSD-storage" = {
    device = "/dev/disk/by-uuid/58A6C9B1A6C98FC4";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "nofail"
      "x-systemd.automount"
      "x-systemd.idle-timeout=60"
    ];
  };
}
