# hosts/haephestus/default.nix — generated by setup-host.sh
{ config, pkgs, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/common
    ../../modules/audio
    ../../modules/gaming
    inputs.noctalia.nixosModules.default
  ];

  networking.hostName = "haephestus";
  nixpkgs.config.allowUnfree = true;

  boot.loader.grub.enable = false;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  services.printing.enable = true;

  # mouse options
  services.xserver.dpi = 180;
  services.xserver.upscaleDefaultCursor = true;

  # disable fprintd
  security.pam.services.greetd.fprintAuth = false;

  # nvidia
  services.xserver.videoDrivers = [ "nvidia" ];
  boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  hardware = {
    graphics.enable = true;
    nvidia = {
      open = false;
      nvidiaSettings = true;
      modesetting.enable = true;
      powerManagement.enable = false;
      powerManagement.finegrained = false;
      package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
    };
  };
  nixpkgs.config.nvidia.acceptLicense = true;
  environment.sessionVariables = {
    #GBM_BACKEND = "nvidia-drm";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    LIBVA_DRIVER_NAME = "nvidia";
    NVD_BACKEND = "direct";
  };

  # bluetooth
  hardware.firmware = [ pkgs.linux-firmware ];
  avalanche.bluetooth = {
    enable = true;
    intelCoexFix = false; # uses Realtek adapter
  };

  system.stateVersion = "25.11"; # dont touch unless extremely sure

  # Windows drives
  environment.systemPackages = [ pkgs.ntfs3g ];
  
  fileSystems."/mnt/HDD-Bulk" = {
    device = "/dev/disk/by-uuid/3454A76254A72618";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "nofail"
      "x-systemd.automount"
      "x-systemd.idle-timeout=60"
      "force"
    ];
  };
  
  fileSystems."/mnt/SSD-storage" = {
    device = "/dev/disk/by-uuid/58A6C9B1A6C98FC4";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "nofail"
      "x-systemd.automount"
      "x-systemd.idle-timeout=60"
      "force"
    ];
  };
}
