# hosts/test123/default.nix — generated by setup-host.sh
{ config, pkgs, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/common
    ../../modules/T480
    inputs.noctalia.nixosModules.default
  ];

  networking.hostName = "test123";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enable = false;
  services.printing.enable = true;

  # ── SOPS ──────────────────────────────────────────────────────────────────
  # Uncomment after adding this host's age public key to secrets.yaml and
  # re-encrypting: sops updatekeys secrets/secrets.yaml
  #
  # sops = {
  #   defaultSopsFile  = ../../secrets/secrets.yaml;
  #   defaultSopsFormat = "yaml";
  #   age.keyFile      = "/home/mntn/.config/sops/age/keys.txt";
  #   secrets = {
  #     "github_email"          = { };
  #     "wifi/eduroam/email"    = { };
  #     "wifi/eduroam/password" = { };
  #   };
  # };

  system.stateVersion = "25.11";
}
